"""empty message

Revision ID: 43a9131fb0f6
Revises: 
Create Date: 2019-02-22 23:48:47.152648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a9131fb0f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address1', sa.String(length=64), nullable=True),
    sa.Column('address2', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('zipCode', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('customerID')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_table('payments',
    sa.Column('paymentID', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('paymentID')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shippers',
    sa.Column('shipperID', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contactName', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('shipperID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('suppliers',
    sa.Column('supplierID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('customer_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_ID'], ['customers.customerID'], ),
    sa.PrimaryKeyConstraint('supplierID')
    )
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=True)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('wasOrdered', sa.Boolean(), nullable=True),
    sa.Column('wasAccepted', sa.Boolean(), nullable=True),
    sa.Column('dateOrdered', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('wasFulfilled', sa.Boolean(), nullable=True),
    sa.Column('total', sa.Numeric(scale=2), nullable=True),
    sa.Column('customer_ID', sa.Integer(), nullable=True),
    sa.Column('payment_ID', sa.Integer(), nullable=True),
    sa.Column('shipper_ID', sa.Integer(), nullable=True),
    sa.Column('supplier_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_ID'], ['customers.customerID'], ),
    sa.ForeignKeyConstraint(['payment_ID'], ['payments.paymentID'], ),
    sa.ForeignKeyConstraint(['shipper_ID'], ['shippers.shipperID'], ),
    sa.ForeignKeyConstraint(['supplier_ID'], ['suppliers.supplierID'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_index(op.f('ix_orders_dateOrdered'), 'orders', ['dateOrdered'], unique=False)
    op.create_table('products',
    sa.Column('productID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Numeric(scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('supplier_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_ID'], ['suppliers.supplierID'], ),
    sa.PrimaryKeyConstraint('productID')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('order_details',
    sa.Column('orderDetailsID', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=215), nullable=True),
    sa.Column('dob', sa.String(length=32), nullable=True),
    sa.Column('height', sa.Numeric(scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(scale=2), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('is_message', sa.Boolean(), nullable=True),
    sa.Column('order_ID', sa.Integer(), nullable=True),
    sa.Column('product_ID', sa.Integer(), nullable=True),
    sa.Column('shipper_ID', sa.Integer(), nullable=True),
    sa.Column('customer_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_ID'], ['customers.customerID'], ),
    sa.ForeignKeyConstraint(['order_ID'], ['orders.orderID'], ),
    sa.ForeignKeyConstraint(['product_ID'], ['products.productID'], ),
    sa.ForeignKeyConstraint(['shipper_ID'], ['shippers.shipperID'], ),
    sa.PrimaryKeyConstraint('orderDetailsID')
    )
    op.create_index(op.f('ix_order_details_dob'), 'order_details', ['dob'], unique=False)
    op.create_index(op.f('ix_order_details_name'), 'order_details', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_details_name'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_dob'), table_name='order_details')
    op.drop_table('order_details')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_dateOrdered'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('shippers')
    op.drop_table('roles')
    op.drop_table('payments')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
