"""empty message

Revision ID: ec9427cdf3d5
Revises: 
Create Date: 2019-01-07 13:13:41.321929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9427cdf3d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('firstName', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('customerID')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_firstName'), 'customers', ['firstName'], unique=False)
    op.create_index(op.f('ix_customers_lastName'), 'customers', ['lastName'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('authorization', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('orders',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.String(length=32), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('wasOrdered', sa.Boolean(), nullable=True),
    sa.Column('dateOrdered', sa.DateTime(), nullable=True),
    sa.Column('wasFulfilled', sa.Boolean(), nullable=True),
    sa.Column('customer_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_ID'], ['customers.customerID'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_lastName'), table_name='customers')
    op.drop_index(op.f('ix_customers_firstName'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
